/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KameraRouteImport } from './routes/kamera'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulIndexRouteImport } from './routes/modul/index'
import { Route as LatihanIndexRouteImport } from './routes/latihan/index'
import { Route as ModulSlugRouteImport } from './routes/modul/$slug'
import { Route as LatihanSlugRouteImport } from './routes/latihan/$slug'
import { Route as AuthenticatedBicaraIndexRouteImport } from './routes/_authenticated/bicara/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KameraRoute = KameraRouteImport.update({
  id: '/kamera',
  path: '/kamera',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulIndexRoute = ModulIndexRouteImport.update({
  id: '/modul/',
  path: '/modul/',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanIndexRoute = LatihanIndexRouteImport.update({
  id: '/latihan/',
  path: '/latihan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulSlugRoute = ModulSlugRouteImport.update({
  id: '/modul/$slug',
  path: '/modul/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanSlugRoute = LatihanSlugRouteImport.update({
  id: '/latihan/$slug',
  path: '/latihan/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBicaraIndexRoute =
  AuthenticatedBicaraIndexRouteImport.update({
    id: '/bicara/',
    path: '/bicara/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kamera': typeof KameraRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/latihan/$slug': typeof LatihanSlugRoute
  '/modul/$slug': typeof ModulSlugRoute
  '/latihan/': typeof LatihanIndexRoute
  '/modul/': typeof ModulIndexRoute
  '/bicara/': typeof AuthenticatedBicaraIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kamera': typeof KameraRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/latihan/$slug': typeof LatihanSlugRoute
  '/modul/$slug': typeof ModulSlugRoute
  '/latihan': typeof LatihanIndexRoute
  '/modul': typeof ModulIndexRoute
  '/bicara': typeof AuthenticatedBicaraIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kamera': typeof KameraRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/latihan/$slug': typeof LatihanSlugRoute
  '/modul/$slug': typeof ModulSlugRoute
  '/latihan/': typeof LatihanIndexRoute
  '/modul/': typeof ModulIndexRoute
  '/_authenticated/bicara/': typeof AuthenticatedBicaraIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kamera'
    | '/sitemap.xml'
    | '/latihan/$slug'
    | '/modul/$slug'
    | '/latihan/'
    | '/modul/'
    | '/bicara/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kamera'
    | '/sitemap.xml'
    | '/latihan/$slug'
    | '/modul/$slug'
    | '/latihan'
    | '/modul'
    | '/bicara'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/kamera'
    | '/sitemap.xml'
    | '/latihan/$slug'
    | '/modul/$slug'
    | '/latihan/'
    | '/modul/'
    | '/_authenticated/bicara/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KameraRoute: typeof KameraRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LatihanSlugRoute: typeof LatihanSlugRoute
  ModulSlugRoute: typeof ModulSlugRoute
  LatihanIndexRoute: typeof LatihanIndexRoute
  ModulIndexRoute: typeof ModulIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamera': {
      id: '/kamera'
      path: '/kamera'
      fullPath: '/kamera'
      preLoaderRoute: typeof KameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modul/': {
      id: '/modul/'
      path: '/modul'
      fullPath: '/modul/'
      preLoaderRoute: typeof ModulIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan/': {
      id: '/latihan/'
      path: '/latihan'
      fullPath: '/latihan/'
      preLoaderRoute: typeof LatihanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modul/$slug': {
      id: '/modul/$slug'
      path: '/modul/$slug'
      fullPath: '/modul/$slug'
      preLoaderRoute: typeof ModulSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan/$slug': {
      id: '/latihan/$slug'
      path: '/latihan/$slug'
      fullPath: '/latihan/$slug'
      preLoaderRoute: typeof LatihanSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bicara/': {
      id: '/_authenticated/bicara/'
      path: '/bicara'
      fullPath: '/bicara/'
      preLoaderRoute: typeof AuthenticatedBicaraIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBicaraIndexRoute: typeof AuthenticatedBicaraIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBicaraIndexRoute: AuthenticatedBicaraIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KameraRoute: KameraRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LatihanSlugRoute: LatihanSlugRoute,
  ModulSlugRoute: ModulSlugRoute,
  LatihanIndexRoute: LatihanIndexRoute,
  ModulIndexRoute: ModulIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
