GRANT SELECT, INSERT, UPDATE, DELETE ON public.bilik TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ahli_bilik TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.mesej TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.bacaan TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.laporan TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pos TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.suka_pos TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profil TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.set_kad TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.kad TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.undian TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.undian_pilihan TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.undian_undi TO authenticated;
GRANT SELECT ON public.kata_tapis TO authenticated;

GRANT ALL ON public.bilik TO service_role;
GRANT ALL ON public.ahli_bilik TO service_role;
GRANT ALL ON public.bilik_rahsia TO service_role;
GRANT ALL ON public.mesej TO service_role;
GRANT ALL ON public.bacaan TO service_role;
GRANT ALL ON public.laporan TO service_role;
GRANT ALL ON public.pos TO service_role;
GRANT ALL ON public.suka_pos TO service_role;
GRANT ALL ON public.profil TO service_role;
GRANT ALL ON public.set_kad TO service_role;
GRANT ALL ON public.kad TO service_role;
GRANT ALL ON public.undian TO service_role;
GRANT ALL ON public.undian_pilihan TO service_role;
GRANT ALL ON public.undian_undi TO service_role;
GRANT ALL ON public.kata_tapis TO service_role;